import type { HudTemplate } from "./types";
/**
 * デフォルト画面サイズ（フルHD）
 */
const DEFAULT_SCREEN_SIZE = {
  width: 1920,
  height: 1080,
  preset: "1920x1080" as const,
};

/**
 * ミニマルテンプレート集
 * シンプルで洗練されたデザイン
 */
export const minimalTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "minimal-corner",
      name: "Corner Stats",
      nameKey: "obs.templates.minimalCorner.name",
      description: "Clean corner display with essential stats",
      descriptionKey: "obs.templates.minimalCorner.description",
      category: "minimal",
      tags: ["simple", "clean", "corner"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#10b981",
        size: { width: 200, height: 2 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 20 },
        visible: true,
        fontSize: 16,
        text: "🏆 {winCount}勝 {loseCount}敗\n📊 勝率 {winRate}%",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 12,
        boxShadow: "0 4px 16px rgba(16, 185, 129, 0.4)",
      },
    ],
  },
  {
    metadata: {
      id: "minimal-topbar",
      name: "Top Bar",
      nameKey: "obs.templates.minimalTopbar.name",
      description: "Horizontal top bar layout",
      descriptionKey: "obs.templates.minimalTopbar.description",
      category: "minimal",
      tags: ["simple", "horizontal", "top"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#10b981",
        size: { width: 400, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 20 },
        visible: true,
        fontSize: 18,
        text: "🎮 戦績: {winCount}W-{loseCount}L ({winRate}%)  •  Total: {totalMatches}",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 12,
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.7)",
      },
    ],
  },
  {
    metadata: {
      id: "minimal-side",
      name: "Side Panel",
      nameKey: "obs.templates.minimalSide.name",
      description: "Vertical side panel",
      descriptionKey: "obs.templates.minimalSide.description",
      category: "minimal",
      tags: ["simple", "vertical", "side"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 3,
        lineColor: "#8b5cf6",
        size: { width: 3, height: 200 },
      },
      {
        type: "variableText",
        position: { x: 20, y: 10 },
        visible: true,
        fontSize: 16,
        text: "🏆 勝利\n{winCount}\n\n💀 敗北\n{loseCount}\n\n� 勝率\n{winRate}%",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 14,
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.7)",
      },
    ],
  },
];

/**
 * 詳細テンプレート集
 * 豊富な情報を表示
 */
export const detailedTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "detailed-dashboard",
      name: "Dashboard",
      nameKey: "obs.templates.detailedDashboard.name",
      description: "Complete stats dashboard",
      descriptionKey: "obs.templates.detailedDashboard.description",
      category: "detailed",
      tags: ["complete", "dashboard", "stats"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "variableText",
        position: { x: 10, y: 10 },
        visible: true,
        fontSize: 22,
        text: "📊 今日の戦績ダッシュボード",
        textColor: "#3b82f6",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 18,
        boxShadow: "0 6px 20px rgba(0, 0, 0, 0.8)",
      },
      {
        type: "variableText",
        position: { x: 10, y: 80 },
        visible: true,
        fontSize: 16,
        text: "🏆 勝利数: {winCount}  |  💀 敗北数: {loseCount}\n📈 勝率: {winRate}%  |  🎮 総試合: {totalMatches}",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 18,
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.7)",
      },
      {
        type: "todayTrendChart",
        position: { x: 10, y: 170 },
        visible: true,
        size: { width: 450, height: 350 },
      },
    ],
  },
  {
    metadata: {
      id: "detailed-split",
      name: "Split View",
      nameKey: "obs.templates.detailedSplit.name",
      description: "Stats and chart side by side",
      descriptionKey: "obs.templates.detailedSplit.description",
      category: "detailed",
      tags: ["split", "chart", "detailed"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "variableText",
        position: { x: 10, y: 10 },
        visible: true,
        fontSize: 20,
        text: "� 戦績トラッキング",
        textColor: "#10b981",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 20,
        boxShadow: "0 6px 20px rgba(0, 0, 0, 0.8)",
      },
      {
        type: "todayTrendChart",
        position: { x: 10, y: 85 },
        visible: true,
        size: { width: 550, height: 350 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 455 },
        visible: true,
        fontSize: 16,
        text: "🏆 {winCount}勝  💀 {loseCount}敗\n📊 勝率 {winRate}%  🎮 {totalMatches}試合",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 18,
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.7)",
      },
    ],
  },
];

/**
 * ストリーミング配信向けテンプレート集
 * 視聴者に見やすいデザイン
 */
export const streamingTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "streaming-ticker",
      name: "Bottom Ticker",
      nameKey: "obs.templates.streamingTicker.name",
      description: "News ticker style at bottom",
      descriptionKey: "obs.templates.streamingTicker.description",
      category: "streaming",
      tags: ["ticker", "bottom", "streaming"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 0, y: 0 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 5,
        lineColor: "#ef4444",
        size: { width: 1920, height: 5 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 10 },
        visible: true,
        fontSize: 18,
        text: "🔴 LIVE  |  🏆 {winCount}勝 {loseCount}敗  |  📊 勝率 {winRate}%  |  🎮 総試合 {totalMatches}",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 12,
        boxShadow: "0 -8px 24px rgba(0, 0, 0, 0.8)",
      },
    ],
  },
  {
    metadata: {
      id: "streaming-corner-overlay",
      name: "Corner Overlay",
      nameKey: "obs.templates.streamingCornerOverlay.name",
      description: "Non-intrusive corner overlay",
      descriptionKey: "obs.templates.streamingCornerOverlay.description",
      category: "streaming",
      tags: ["corner", "overlay", "minimal"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 1720, y: 15 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 5,
        lineColor: "#8b5cf6",
        size: { width: 5, height: 110 },
      },
      {
        type: "variableText",
        position: { x: 1738, y: 20 },
        visible: true,
        fontSize: 16,
        text: "🏆 W {winCount}\n💀 L {loseCount}\n📈 {winRate}%",
        textColor: "#ffffff",
        textAlign: "right",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 12,
        boxShadow: "0 6px 20px rgba(139, 92, 246, 0.6)",
      },
      {
        type: "line",
        position: { x: 1720, y: 130 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#8b5cf6",
        size: { width: 180, height: 4 },
      },
    ],
  },
  {
    metadata: {
      id: "streaming-title-safe",
      name: "Title Safe Zone",
      nameKey: "obs.templates.streamingTitleSafe.name",
      description: "Centered in title-safe area",
      descriptionKey: "obs.templates.streamingTitleSafe.description",
      category: "streaming",
      tags: ["centered", "title-safe", "broadcast"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "variableText",
        position: { x: 10, y: 10 },
        visible: true,
        fontSize: 28,
        text: "🎮 戦績統計",
        textColor: "#3b82f6",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 24,
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.8)",
      },
      {
        type: "line",
        position: { x: 10, y: 90 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#3b82f6",
        size: { width: 400, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 103 },
        visible: true,
        fontSize: 28,
        text: "{winCount} - {loseCount}",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 24,
        boxShadow: "0 6px 24px rgba(0, 0, 0, 0.7)",
      },
      {
        type: "variableText",
        position: { x: 10, y: 185 },
        visible: true,
        fontSize: 18,
        text: "📊 {winRate}%",
        textColor: "#94a3b8",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 14,
        boxShadow: "0 4px 16px rgba(0, 0, 0, 0.6)",
      },
    ],
  },
];

/**
 * 競技向けテンプレート集
 * プロフェッショナルで見やすいデザイン
 */
export const competitiveTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "competitive-esports",
      name: "E-Sports HUD",
      nameKey: "obs.templates.competitiveEsports.name",
      description: "Professional tournament style",
      descriptionKey: "obs.templates.competitiveEsports.description",
      category: "competitive",
      tags: ["esports", "tournament", "professional"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 0, y: 0 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 5,
        lineColor: "#ef4444",
        size: { width: 500, height: 5 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 10 },
        visible: true,
        fontSize: 20,
        text: "⚡ RECORD: {winCount}W-{loseCount}L ({winRate}%)",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 14,
        boxShadow: "0 10px 40px rgba(239, 68, 68, 0.7)",
      },
      {
        type: "line",
        position: { x: 0, y: 58 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#dc2626",
        size: { width: 500, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 435, y: 14 },
        visible: true,
        fontSize: 16,
        text: "🎮 {totalMatches}",
        textColor: "#94a3b8",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 10,
        boxShadow: "0 6px 20px rgba(0, 0, 0, 0.6)",
      },
    ],
  },
  {
    metadata: {
      id: "competitive-scoreboard",
      name: "Scoreboard",
      nameKey: "obs.templates.competitiveScoreboard.name",
      description: "Clear scoreboard layout",
      descriptionKey: "obs.templates.competitiveScoreboard.description",
      category: "competitive",
      tags: ["scoreboard", "clear", "readable"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 6,
        lineColor: "#fbbf24",
        size: { width: 280, height: 6 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 25 },
        visible: true,
        fontSize: 40,
        text: "{winCount} - {loseCount}",
        textColor: "#fbbf24",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 24,
        boxShadow: "0 12px 40px rgba(251, 191, 36, 0.6)",
      },
      {
        type: "line",
        position: { x: 10, y: 120 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#475569",
        size: { width: 280, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 130 },
        visible: true,
        fontSize: 18,
        text: "📊 勝率 {winRate}%  •  🎮 総試合数 {totalMatches}",
        textColor: "#cbd5e1",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 12,
        boxShadow: "0 6px 20px rgba(0, 0, 0, 0.6)",
      },
      {
        type: "line",
        position: { x: 10, y: 180 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#fbbf24",
        size: { width: 280, height: 4 },
      },
    ],
  },
  {
    metadata: {
      id: "competitive-analyst",
      name: "Analyst View",
      nameKey: "obs.templates.competitiveAnalyst.name",
      description: "Detailed analytics for commentary",
      descriptionKey: "obs.templates.competitiveAnalyst.description",
      category: "competitive",
      tags: ["analyst", "detailed", "commentary"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#06b6d4",
        size: { width: 400, height: 4 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 20 },
        visible: true,
        fontSize: 18,
        text: "📈 戦績: {winCount}勝 {loseCount}敗\n🎯 勝率: {winRate}% ({totalMatches}戦)",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 16,
        boxShadow: "0 -12px 32px rgba(6, 182, 212, 0.5)",
      },
      {
        type: "line",
        position: { x: 420, y: 20 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 3,
        lineColor: "#475569",
        size: { width: 3, height: 105 },
      },
      {
        type: "line",
        position: { x: 10, y: 121 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#0891b2",
        size: { width: 400, height: 3 },
      },
    ],
  },
];

/**
 * プレミアムテンプレート集
 * 最高級のデザインと視覚効果
 */
export const premiumTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "premium-neon-glow",
      name: "Neon Glow",
      nameKey: "obs.templates.premiumNeonGlow.name",
      description: "Cyberpunk neon aesthetic",
      descriptionKey: "obs.templates.premiumNeonGlow.description",
      category: "premium",
      tags: ["cyberpunk", "neon", "futuristic"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 5,
        lineColor: "#ec4899",
        size: { width: 5, height: 220 },
      },
      {
        type: "variableText",
        position: { x: 20, y: 10 },
        visible: true,
        fontSize: 20,
        text: "⚡ WINS\n{winCount}",
        textColor: "#ec4899",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 16,
        boxShadow: "0 0 30px rgba(236, 72, 153, 0.8), 0 6px 24px rgba(0, 0, 0, 0.9)",
      },
      {
        type: "variableText",
        position: { x: 20, y: 120 },
        visible: true,
        fontSize: 20,
        text: "💀 LOSS\n{loseCount}",
        textColor: "#8b5cf6",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 16,
        boxShadow: "0 0 30px rgba(139, 92, 246, 0.8), 0 6px 24px rgba(0, 0, 0, 0.9)",
      },
      {
        type: "line",
        position: { x: 10, y: 220 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#06b6d4",
        size: { width: 195, height: 4 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 235 },
        visible: true,
        fontSize: 22,
        text: "{winRate}%",
        textColor: "#06b6d4",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 14,
        boxShadow: "0 0 30px rgba(6, 182, 212, 0.8), 0 6px 24px rgba(0, 0, 0, 0.9)",
      },
    ],
  },
  {
    metadata: {
      id: "premium-gradient-flow",
      name: "Gradient Flow",
      nameKey: "obs.templates.premiumGradientFlow.name",
      description: "Smooth gradient animations",
      descriptionKey: "obs.templates.premiumGradientFlow.description",
      category: "premium",
      tags: ["gradient", "smooth", "elegant"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 10, y: 10 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#667eea",
        size: { width: 560, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 25 },
        visible: true,
        fontSize: 26,
        text: "🌟 今日の戦績",
        textColor: "#667eea",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
      },
      {
        type: "variableText",
        position: { x: 10, y: 75 },
        visible: true,
        fontSize: 34,
        text: "{winCount}勝 {loseCount}敗",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(102, 126, 234, 0.2)",
        padding: 22,
        boxShadow: "0 10px 32px rgba(102, 126, 234, 0.6)",
      },
      {
        type: "line",
        position: { x: 10, y: 170 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#764ba2",
        size: { width: 420, height: 2 },
      },
      {
        type: "variableText",
        position: { x: 10, y: 185 },
        visible: true,
        fontSize: 20,
        text: "📊 勝率 {winRate}%  •  🎮 {totalMatches}試合",
        textColor: "#cbd5e1",
        textAlign: "left",
        backgroundColor: "rgba(118, 75, 162, 0.2)",
        padding: 14,
        boxShadow: "0 6px 18px rgba(118, 75, 162, 0.5)",
      },
    ],
  },
  {
    metadata: {
      id: "premium-ultra-clean",
      name: "Ultra Clean",
      nameKey: "obs.templates.premiumUltraClean.name",
      description: "Minimalist perfection",
      descriptionKey: "obs.templates.premiumUltraClean.description",
      category: "premium",
      tags: ["minimal", "clean", "perfection"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "variableText",
        position: { x: 10, y: 10 },
        visible: true,
        fontSize: 50,
        text: "{winCount} - {loseCount}",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "0 12px 48px rgba(255, 255, 255, 0.2)",
      },
      {
        type: "variableText",
        position: { x: 10, y: 100 },
        visible: true,
        fontSize: 22,
        text: "{winRate}%",
        textColor: "#64748b",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
      },
      {
        type: "line",
        position: { x: 10, y: 145 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#334155",
        size: { width: 220, height: 2 },
      },
    ],
  },
];

/**
 * 全テンプレート
 */
export const allTemplates: HudTemplate[] = [...minimalTemplates, ...detailedTemplates, ...streamingTemplates, ...competitiveTemplates, ...premiumTemplates];
