import type { HudTemplate } from "./types";
/**
 * デフォルト画面サイズ（フルHD）
 */
const DEFAULT_SCREEN_SIZE = {
  width: 1920,
  height: 1080,
  preset: "1920x1080" as const,
};

/**
 * ミニマルテンプレート集
 * シンプルで洗練されたデザイン
 */
export const minimalTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "minimal-corner",
      name: "Corner Stats",
      nameKey: "obs.templates.minimalCorner.name",
      description: "Clean corner display with essential stats",
      descriptionKey: "obs.templates.minimalCorner.description",
      category: "minimal",
      tags: ["simple", "clean", "corner"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 1620, y: 15 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#10b981",
        size: { width: 280, height: 2 },
      },
      {
        type: "variableText",
        position: { x: 1650, y: 30 },
        visible: true,
        fontSize: 22,
        text: "🏆 {winCount}勝 {loseCount}敗\n📊 勝率 {winRate}%",
        textColor: "#ffffff",
        textAlign: "right",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 20,
        boxShadow: "0 4px 16px rgba(16, 185, 129, 0.4)",
      },
    ],
  },
  {
    metadata: {
      id: "minimal-top-bar",
      name: "Top Bar",
      nameKey: "obs.templates.minimalTopBar.name",
      description: "Centered top bar with key metrics",
      descriptionKey: "obs.templates.minimalTopBar.description",
      category: "minimal",
      tags: ["simple", "top", "centered"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 660, y: 15 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#667eea",
        size: { width: 600, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 760, y: 35 },
        visible: true,
        fontSize: 24,
        text: "⚔️ {winCount}W - {loseCount}L  •  {winRate}%  •  {totalMatches}試合",
        textColor: "#ffffff",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 18,
        boxShadow: "0 6px 20px rgba(102, 126, 234, 0.5)",
      },
      {
        type: "line",
        position: { x: 660, y: 105 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#667eea",
        size: { width: 600, height: 2 },
      },
    ],
  },
  {
    metadata: {
      id: "minimal-side-panel",
      name: "Side Panel",
      nameKey: "obs.templates.minimalSidePanel.name",
      description: "Vertical side panel layout",
      descriptionKey: "obs.templates.minimalSidePanel.description",
      category: "minimal",
      tags: ["vertical", "side", "compact"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 18, y: 280 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 4,
        lineColor: "#8b5cf6",
        size: { width: 4, height: 220 },
      },
      {
        type: "variableText",
        position: { x: 35, y: 300 },
        visible: true,
        fontSize: 20,
        text: "✅ 勝利: {winCount}\n❌ 敗北: {loseCount}\n📈 勝率: {winRate}%\n🎮 試合: {totalMatches}",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 20,
        boxShadow: "0 4px 16px rgba(139, 92, 246, 0.5)",
      },
      {
        type: "line",
        position: { x: 18, y: 505 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#8b5cf6",
        size: { width: 240, height: 3 },
      },
    ],
  },
];

/**
 * 詳細テンプレート集
 * 豊富な情報を表示
 */
export const detailedTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "detailed-dashboard",
      name: "Full Dashboard",
      nameKey: "obs.templates.detailedDashboard.name",
      description: "Comprehensive stats dashboard",
      descriptionKey: "obs.templates.detailedDashboard.description",
      category: "detailed",
      tags: ["complete", "dashboard", "analytics"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 40, y: 40 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#667eea",
        size: { width: 620, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 50, y: 60 },
        visible: true,
        fontSize: 32,
        text: "📊 戦績レポート {winCount}-{loseCount}",
        textColor: "#667eea",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
      },
      {
        type: "variableText",
        position: { x: 50, y: 115 },
        visible: true,
        fontSize: 18,
        text: "勝率 {winRate}% • 総試合数 {totalMatches}戦",
        textColor: "#94a3b8",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
      },
      {
        type: "statsCombo",
        position: { x: 50, y: 160 },
        visible: true,
        fontSize: 20,
        backgroundColor: "rgba(15, 23, 42, 0.85)",
        padding: 28,
        boxShadow: "0 8px 24px rgba(0, 0, 0, 0.6)",
        comboItems: ["winCount", "loseCount", "winRate", "totalMatches"],
      },
      {
        type: "todayTrendChart",
        position: { x: 50, y: 390 },
        visible: true,
        fontSize: 14,
        backgroundColor: "rgba(15, 23, 42, 0.85)",
        padding: 24,
        boxShadow: "0 8px 24px rgba(0, 0, 0, 0.6)",
        size: { width: 620, height: 420 },
      },
    ],
  },
  {
    metadata: {
      id: "detailed-split-view",
      name: "Split View",
      nameKey: "obs.templates.detailedSplitView.name",
      description: "Stats and chart side by side",
      descriptionKey: "obs.templates.detailedSplitView.description",
      category: "detailed",
      tags: ["split", "chart", "balanced"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "variableText",
        position: { x: 50, y: 45 },
        visible: true,
        fontSize: 28,
        text: "🎯 今日の成績",
        textColor: "#60a5fa",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
      },
      {
        type: "line",
        position: { x: 50, y: 95 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#60a5fa",
        size: { width: 300, height: 2 },
      },
      {
        type: "statsCombo",
        position: { x: 50, y: 120 },
        visible: true,
        fontSize: 22,
        backgroundColor: "rgba(15, 23, 42, 0.95)",
        padding: 32,
        boxShadow: "0 12px 32px rgba(0, 0, 0, 0.7)",
        comboItems: ["winCount", "loseCount", "winRate", "totalMatches"],
      },
      {
        type: "line",
        position: { x: 430, y: 45 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 3,
        lineColor: "#475569",
        size: { width: 3, height: 480 },
      },
      {
        type: "todayTrendChart",
        position: { x: 460, y: 45 },
        visible: true,
        fontSize: 14,
        backgroundColor: "rgba(15, 23, 42, 0.95)",
        padding: 24,
        boxShadow: "0 12px 32px rgba(0, 0, 0, 0.7)",
        size: { width: 740, height: 480 },
      },
    ],
  },
];

/**
 * ストリーミング配信向けテンプレート集
 * 視聴者に見やすいデザイン
 */
export const streamingTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "streaming-bottom-ticker",
      name: "Bottom Ticker",
      nameKey: "obs.templates.streamingBottomTicker.name",
      description: "Bottom screen ticker with stats",
      descriptionKey: "obs.templates.streamingBottomTicker.description",
      category: "streaming",
      tags: ["bottom", "ticker", "viewer-friendly"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 0, y: 1025 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#667eea",
        size: { width: 1920, height: 4 },
      },
      {
        type: "variableText",
        position: { x: 680, y: 1043 },
        visible: true,
        fontSize: 26,
        text: "⚔️ {winCount}勝 {loseCount}敗  •  📊 勝率 {winRate}%  •  🎮 総試合数 {totalMatches}",
        textColor: "#ffffff",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 18,
        boxShadow: "0 -8px 24px rgba(0, 0, 0, 0.7)",
      },
      {
        type: "line",
        position: { x: 0, y: 1076 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#764ba2",
        size: { width: 1920, height: 2 },
      },
    ],
  },
  {
    metadata: {
      id: "streaming-corner-overlay",
      name: "Corner Overlay",
      nameKey: "obs.templates.streamingCornerOverlay.name",
      description: "Non-intrusive corner overlay",
      descriptionKey: "obs.templates.streamingCornerOverlay.description",
      category: "streaming",
      tags: ["corner", "overlay", "minimal"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 1620, y: 15 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 5,
        lineColor: "#8b5cf6",
        size: { width: 5, height: 160 },
      },
      {
        type: "variableText",
        position: { x: 1645, y: 25 },
        visible: true,
        fontSize: 22,
        text: "🏆 W {winCount}\n💀 L {loseCount}\n📈 {winRate}%",
        textColor: "#ffffff",
        textAlign: "right",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 18,
        boxShadow: "0 6px 20px rgba(139, 92, 246, 0.6)",
      },
      {
        type: "line",
        position: { x: 1620, y: 180 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#8b5cf6",
        size: { width: 280, height: 4 },
      },
    ],
  },
  {
    metadata: {
      id: "streaming-title-safe",
      name: "Title Safe Area",
      nameKey: "obs.templates.streamingTitleSafe.name",
      description: "Safe for YouTube/Twitch thumbnails",
      descriptionKey: "obs.templates.streamingTitleSafe.description",
      category: "streaming",
      tags: ["safe-area", "thumbnail", "centered"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 115, y: 220 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 6,
        lineColor: "#3b82f6",
        size: { width: 6, height: 280 },
      },
      {
        type: "variableText",
        position: { x: 140, y: 235 },
        visible: true,
        fontSize: 40,
        text: "🎯 {winCount}勝\n💔 {loseCount}敗\n📊 勝率{winRate}%",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.85)",
        padding: 36,
        boxShadow: "0 12px 40px rgba(0, 0, 0, 0.7)",
        scale: 1.2,
      },
      {
        type: "line",
        position: { x: 115, y: 505 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 5,
        lineColor: "#3b82f6",
        size: { width: 380, height: 5 },
      },
    ],
  },
];

/**
 * 競技向けテンプレート集
 * プロフェッショナルで見やすいデザイン
 */
export const competitiveTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "competitive-esports",
      name: "E-Sports HUD",
      nameKey: "obs.templates.competitiveEsports.name",
      description: "Professional tournament style",
      descriptionKey: "obs.templates.competitiveEsports.description",
      category: "competitive",
      tags: ["esports", "tournament", "professional"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 0, y: 0 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 5,
        lineColor: "#ef4444",
        size: { width: 700, height: 5 },
      },
      {
        type: "variableText",
        position: { x: 20, y: 18 },
        visible: true,
        fontSize: 30,
        text: "⚡ RECORD: {winCount}W-{loseCount}L ({winRate}%)",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 22,
        boxShadow: "0 10px 40px rgba(239, 68, 68, 0.7)",
        scale: 1.15,
      },
      {
        type: "line",
        position: { x: 0, y: 95 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#dc2626",
        size: { width: 700, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 650, y: 23 },
        visible: true,
        fontSize: 20,
        text: "🎮 {totalMatches}",
        textColor: "#94a3b8",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 16,
        boxShadow: "0 6px 20px rgba(0, 0, 0, 0.6)",
      },
    ],
  },
  {
    metadata: {
      id: "competitive-scoreboard",
      name: "Scoreboard",
      nameKey: "obs.templates.competitiveScoreboard.name",
      description: "Clear scoreboard layout",
      descriptionKey: "obs.templates.competitiveScoreboard.description",
      category: "competitive",
      tags: ["scoreboard", "clear", "readable"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 750, y: 15 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 6,
        lineColor: "#fbbf24",
        size: { width: 420, height: 6 },
      },
      {
        type: "variableText",
        position: { x: 800, y: 40 },
        visible: true,
        fontSize: 56,
        text: "{winCount} - {loseCount}",
        textColor: "#fbbf24",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 36,
        boxShadow: "0 12px 40px rgba(251, 191, 36, 0.6)",
        scale: 1.4,
      },
      {
        type: "line",
        position: { x: 750, y: 195 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#475569",
        size: { width: 420, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 810, y: 215 },
        visible: true,
        fontSize: 26,
        text: "📊 勝率 {winRate}%  •  🎮 総試合数 {totalMatches}",
        textColor: "#cbd5e1",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0.9)",
        padding: 18,
        boxShadow: "0 6px 20px rgba(0, 0, 0, 0.6)",
      },
      {
        type: "line",
        position: { x: 750, y: 285 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#fbbf24",
        size: { width: 420, height: 4 },
      },
    ],
  },
  {
    metadata: {
      id: "competitive-analyst",
      name: "Analyst View",
      nameKey: "obs.templates.competitiveAnalyst.name",
      description: "Detailed analytics for commentary",
      descriptionKey: "obs.templates.competitiveAnalyst.description",
      category: "competitive",
      tags: ["analyst", "detailed", "commentary"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 15, y: 915 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#06b6d4",
        size: { width: 550, height: 4 },
      },
      {
        type: "variableText",
        position: { x: 25, y: 935 },
        visible: true,
        fontSize: 24,
        text: "📈 戦績: {winCount}勝 {loseCount}敗\n🎯 勝率: {winRate}% ({totalMatches}戦)",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 24,
        boxShadow: "0 -12px 32px rgba(6, 182, 212, 0.5)",
      },
      {
        type: "line",
        position: { x: 575, y: 935 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 3,
        lineColor: "#475569",
        size: { width: 3, height: 145 },
      },
      {
        type: "line",
        position: { x: 15, y: 1075 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#0891b2",
        size: { width: 550, height: 3 },
      },
    ],
  },
];

/**
 * プレミアムテンプレート集
 * 最高級のデザインと視覚効果
 */
export const premiumTemplates: HudTemplate[] = [
  {
    metadata: {
      id: "premium-neon-glow",
      name: "Neon Glow",
      nameKey: "obs.templates.premiumNeonGlow.name",
      description: "Cyberpunk neon aesthetic",
      descriptionKey: "obs.templates.premiumNeonGlow.description",
      category: "premium",
      tags: ["cyberpunk", "neon", "futuristic"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 1620, y: 480 },
        visible: true,
        lineOrientation: "vertical",
        lineThickness: 6,
        lineColor: "#ec4899",
        size: { width: 6, height: 300 },
      },
      {
        type: "variableText",
        position: { x: 1650, y: 500 },
        visible: true,
        fontSize: 28,
        text: "⚡ WINS\n{winCount}",
        textColor: "#ec4899",
        textAlign: "right",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 24,
        boxShadow: "0 0 40px rgba(236, 72, 153, 0.8), 0 8px 32px rgba(0, 0, 0, 0.9)",
        scale: 1.1,
      },
      {
        type: "variableText",
        position: { x: 1650, y: 630 },
        visible: true,
        fontSize: 28,
        text: "💀 LOSS\n{loseCount}",
        textColor: "#8b5cf6",
        textAlign: "right",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 24,
        boxShadow: "0 0 40px rgba(139, 92, 246, 0.8), 0 8px 32px rgba(0, 0, 0, 0.9)",
        scale: 1.1,
      },
      {
        type: "line",
        position: { x: 1620, y: 785 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 5,
        lineColor: "#06b6d4",
        size: { width: 280, height: 5 },
      },
      {
        type: "variableText",
        position: { x: 1705, y: 805 },
        visible: true,
        fontSize: 32,
        text: "{winRate}%",
        textColor: "#06b6d4",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0.95)",
        padding: 20,
        boxShadow: "0 0 40px rgba(6, 182, 212, 0.8), 0 8px 32px rgba(0, 0, 0, 0.9)",
        scale: 1.2,
      },
    ],
  },
  {
    metadata: {
      id: "premium-gradient-flow",
      name: "Gradient Flow",
      nameKey: "obs.templates.premiumGradientFlow.name",
      description: "Smooth gradient animations",
      descriptionKey: "obs.templates.premiumGradientFlow.description",
      category: "premium",
      tags: ["gradient", "smooth", "elegant"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "line",
        position: { x: 50, y: 50 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 4,
        lineColor: "#667eea",
        size: { width: 800, height: 4 },
      },
      {
        type: "variableText",
        position: { x: 60, y: 70 },
        visible: true,
        fontSize: 36,
        text: "🌟 今日の戦績",
        textColor: "#667eea",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
        scale: 1.1,
      },
      {
        type: "variableText",
        position: { x: 60, y: 140 },
        visible: true,
        fontSize: 48,
        text: "{winCount}勝 {loseCount}敗",
        textColor: "#ffffff",
        textAlign: "left",
        backgroundColor: "rgba(102, 126, 234, 0.2)",
        padding: 32,
        boxShadow: "0 12px 40px rgba(102, 126, 234, 0.6)",
        scale: 1.2,
      },
      {
        type: "line",
        position: { x: 50, y: 280 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 3,
        lineColor: "#764ba2",
        size: { width: 600, height: 3 },
      },
      {
        type: "variableText",
        position: { x: 60, y: 305 },
        visible: true,
        fontSize: 28,
        text: "📊 勝率 {winRate}%  •  🎮 {totalMatches}試合",
        textColor: "#cbd5e1",
        textAlign: "left",
        backgroundColor: "rgba(118, 75, 162, 0.2)",
        padding: 20,
        boxShadow: "0 8px 24px rgba(118, 75, 162, 0.5)",
      },
    ],
  },
  {
    metadata: {
      id: "premium-ultra-clean",
      name: "Ultra Clean",
      nameKey: "obs.templates.premiumUltraClean.name",
      description: "Minimalist perfection",
      descriptionKey: "obs.templates.premiumUltraClean.description",
      category: "premium",
      tags: ["minimal", "clean", "perfection"],
    },
    screenSize: DEFAULT_SCREEN_SIZE,
    elements: [
      {
        type: "variableText",
        position: { x: 820, y: 500 },
        visible: true,
        fontSize: 72,
        text: "{winCount} - {loseCount}",
        textColor: "#ffffff",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "0 16px 64px rgba(255, 255, 255, 0.2)",
        scale: 1.5,
      },
      {
        type: "variableText",
        position: { x: 890, y: 620 },
        visible: true,
        fontSize: 32,
        text: "{winRate}%",
        textColor: "#64748b",
        textAlign: "center",
        backgroundColor: "rgba(0, 0, 0, 0)",
        padding: 0,
        boxShadow: "none",
      },
      {
        type: "line",
        position: { x: 810, y: 690 },
        visible: true,
        lineOrientation: "horizontal",
        lineThickness: 2,
        lineColor: "#334155",
        size: { width: 300, height: 2 },
      },
    ],
  },
];

/**
 * 全テンプレート
 */
export const allTemplates: HudTemplate[] = [...minimalTemplates, ...detailedTemplates, ...streamingTemplates, ...competitiveTemplates, ...premiumTemplates];
