/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as GraphsRouteImport } from './routes/graphs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObsIndexRouteImport } from './routes/obs/index'
import { Route as HistoriesIndexRouteImport } from './routes/histories/index'
import { Route as ObsWindowRouteImport } from './routes/obs/window'
import { Route as HistoriesIdRouteImport } from './routes/histories/$id'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsRoute = GraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsIndexRoute = ObsIndexRouteImport.update({
  id: '/obs/',
  path: '/obs/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriesIndexRoute = HistoriesIndexRouteImport.update({
  id: '/histories/',
  path: '/histories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsWindowRoute = ObsWindowRouteImport.update({
  id: '/obs/window',
  path: '/obs/window',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriesIdRoute = HistoriesIdRouteImport.update({
  id: '/histories/$id',
  path: '/histories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/graphs': typeof GraphsRoute
  '/new': typeof NewRoute
  '/histories/$id': typeof HistoriesIdRoute
  '/obs/window': typeof ObsWindowRoute
  '/histories': typeof HistoriesIndexRoute
  '/obs': typeof ObsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/graphs': typeof GraphsRoute
  '/new': typeof NewRoute
  '/histories/$id': typeof HistoriesIdRoute
  '/obs/window': typeof ObsWindowRoute
  '/histories': typeof HistoriesIndexRoute
  '/obs': typeof ObsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/graphs': typeof GraphsRoute
  '/new': typeof NewRoute
  '/histories/$id': typeof HistoriesIdRoute
  '/obs/window': typeof ObsWindowRoute
  '/histories/': typeof HistoriesIndexRoute
  '/obs/': typeof ObsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/graphs'
    | '/new'
    | '/histories/$id'
    | '/obs/window'
    | '/histories'
    | '/obs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/graphs'
    | '/new'
    | '/histories/$id'
    | '/obs/window'
    | '/histories'
    | '/obs'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/graphs'
    | '/new'
    | '/histories/$id'
    | '/obs/window'
    | '/histories/'
    | '/obs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  GraphsRoute: typeof GraphsRoute
  NewRoute: typeof NewRoute
  HistoriesIdRoute: typeof HistoriesIdRoute
  ObsWindowRoute: typeof ObsWindowRoute
  HistoriesIndexRoute: typeof HistoriesIndexRoute
  ObsIndexRoute: typeof ObsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs': {
      id: '/graphs'
      path: '/graphs'
      fullPath: '/graphs'
      preLoaderRoute: typeof GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/': {
      id: '/obs/'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof ObsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histories/': {
      id: '/histories/'
      path: '/histories'
      fullPath: '/histories'
      preLoaderRoute: typeof HistoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs/window': {
      id: '/obs/window'
      path: '/obs/window'
      fullPath: '/obs/window'
      preLoaderRoute: typeof ObsWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histories/$id': {
      id: '/histories/$id'
      path: '/histories/$id'
      fullPath: '/histories/$id'
      preLoaderRoute: typeof HistoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  GraphsRoute: GraphsRoute,
  NewRoute: NewRoute,
  HistoriesIdRoute: HistoriesIdRoute,
  ObsWindowRoute: ObsWindowRoute,
  HistoriesIndexRoute: HistoriesIndexRoute,
  ObsIndexRoute: ObsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
